import { faL } from "@fortawesome/free-solid-svg-icons";

const OSRS_MONSTERS = [
  // Level 1 to 10
  {
    monster: "Evil Creature",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Chicken",
    member: false,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Chinchompa (Hunter)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Gnome",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Gnome Woman",
    member: true,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Ragnar (Miscellania)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Duckling",
    member: false,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Spider",
    member: false,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Gnome child",
    member: true,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Einar",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Duck",
    member: false,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Gnome troop",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Rat",
    member: false,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Target",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Halla (miscellania)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Thorhild",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Undead chicken",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Rabbit",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Alrik",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Man",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rannveig",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Ram",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Giant spider",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Rusty",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rabbit (Prifddinas)",
    member: true,
    combat: 2,
    hp: 2000,
  },
  {
    monster: "Narf",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rooster (lvl2)",
    member: true,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Rooster (lvl3)",
    member: true,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Entrana firebird",
    member: true,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Seagull",
    member: false,
    combat: 2,
    hp: 6,
  },
  {
    monster: "Skraeling (Etceteria)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Hengel",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Goblin",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Ragnvald",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Imp",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Jonny the beard",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Jeff",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Skraeling (Etceteria)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Penguin",
    member: true,
    combat: 2,
    hp: 4,
  },
  {
    monster: "Cow calf",
    member: false,
    combat: 2,
    hp: 6,
  },
  {
    monster: "Undead cow",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Skraeling (Miscellania)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Valgerd",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Anja",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Carnivorous chinchompa",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Black chinchompa (Hunter)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Broddi",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Wormbrain",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Thora (Miscellania)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Zombie rat",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Pheasant",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Monkey",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Monk",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Cave goblin",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Sleepwalker",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Giant rat",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Sleepwalker",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Seagull (Icyene Graveyard)",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Gardener",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Drunken man",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Pheasant",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Cuffs",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Eadburg",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "ceolburg",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "Hygd",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "Snake (desert)",
    member: true,
    combat: 5,
    hp: 6,
  },
  {
    monster: "Servant (Burthorpe)",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Snake",
    member: false,
    combat: 5,
    hp: 6,
  },
  {
    monster: "Gnome Driver",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Gnome Archer",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Highwayman",
    member: false,
    combat: 5,
    hp: 13,
  },
  {
    monster: "Gnome Mage",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Penda",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Ocga",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Frog",
    member: false,
    combat: 5,
    hp: 8,
  },
  {
    monster: "Bird",
    member: true,
    combat: 5,
    hp: 5,
  },
  {
    monster: "Bird (lvl11)",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Boar (lvl5)",
    member: true,
    combat: 5,
    hp: 5,
  },
  {
    monster: "Boar (lvl7)",
    member: true,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Breoca",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Bat",
    member: true,
    combat: 6,
    hp: 8,
  },
  {
    monster: "Mugger",
    member: false,
    combat: 6,
    hp: 8,
  },
  {
    monster: "Chompy bird",
    member: true,
    combat: 6,
    hp: 10,
  },
  {
    monster: "Cave bug",
    member: true,
    combat: 6,
    hp: 5,
  },
  {
    monster: "Farmer",
    member: false,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Dwarf (lvl7)",
    member: false,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dwarf (lvl10)",
    member: false,
    combat: 10,
    hp: 16,
  },
  {
    monster: "Dwarf (lvl11)",
    member: false,
    combat: 11,
    hp: 18,
  },
  {
    monster: "Imp",
    member: false,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dark wizard",
    member: false,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Dark wizard (lvl11)",
    member: true,
    combat: 11,
    hp: 15,
  },
  {
    monster: "Dark wizard (lvl20)",
    member: false,
    combat: 20,
    hp: 24,
  },
  {
    monster: "Crawling hand (lvl7)",
    member: true,
    combat: 7,
    hp: 15,
  },
  {
    monster: "Crawling hand (lvl8)",
    member: true,
    combat: 8,
    hp: 16,
  },
  {
    monster: "Revenant imp",
    member: true,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dark warrior",
    member: false,
    combat: 8,
    hp: 17,
  },
  {
    monster: "Barbarian (lvl8)",
    member: false,
    combat: 8,
    hp: 14,
  },
  {
    monster: "Scarab Swarm (Tombs of Amascut)",
    member: true,
    combat: 8,
    hp: 10,
  },
  {
    monster: "Barbarian (lvl9)",
    member: false,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Barbarian (lvl10)",
    member: false,
    combat: 10,
    hp: 18,
  },
  {
    monster: "Barbarian (Barbarian Camp)",
    member: true,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Wizard",
    member: false,
    combat: 9,
    hp: 14,
  },
  {
    monster: "Blessed giant rat",
    member: true,
    combat: 9,
    hp: 30,
  },
  {
    monster: "Al Kharid warrior",
    member: false,
    combat: 9,
    hp: 19,
  },
  {
    monster: "Myre Blamish Snail",
    member: true,
    combat: 9,
    hp: 8,
  },
  {
    monster: "Myre Blamish Snail (Pointed)",
    member: true,
    combat: 10,
    hp: 13,
  },
  {
    monster: "Ochre Blamish Snail (Round)",
    member: true,
    combat: 10,
    hp: 10,
  },
  {
    monster: "Ochre Blamish Snail (Pointed)",
    member: true,
    combat: 15,
    hp: 20,
  },
  {
    monster: "Jubbly bird",
    member: true,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Thug",
    member: true,
    combat: 9,
    hp: 18,
  },
  {
    monster: "Rowdy slave",
    member: true,
    combat: 10,
    hp: 16,
  },
  {
    monster: "Big frog",
    member: true,
    combat: 10,
    hp: 18,
  },
  {
    monster: "Guard (dwarf)",
    member: false,
    combat: 10,
    hp: 16,
  },
  // Level 11 to 20
  {
    monster: "Cave goblin miner",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Plague frog",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Shipyard worker",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Wolf (lvl11)",
    member: false,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Goblin (Vault of War)",
    member: false,
    combat: 11,
    hp: 7,
  },
  {
    monster: "Goblin (lvl25)",
    member: false,
    combat: 25,
    hp: 26,
  },
  {
    monster: "Animated Bronze Armour",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Mourner (lvl11)",
    member: true,
    combat: 11,
    hp: 19,
  },
  {
    monster: "Venenatis' Spiderling",
    member: true,
    combat: 12,
    hp: 5,
  },
  {
    monster: "Small Lizard",
    member: true,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Dungeon rat",
    member: true,
    combat: 12,
    hp: 12,
  },
  {
    monster: "Grave scorpion",
    member: true,
    combat: 12,
    hp: 12,
  },
  {
    monster: "H.A.M. Guard (lvl12)",
    member: true,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Spindel's Spiderling",
    member: true,
    combat: 12,
    hp: 5,
  },
  {
    monster: "Goblin (God Wars Dungeon) Banner",
    member: true,
    combat: 12,
    hp: 3,
  },
  {
    monster: "Enraged Boar",
    member: false,
    combat: 12,
    hp: 25,
  },
  {
    monster: "Goblin (God Wars Dungeon)",
    member: false,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Goblin (lvl13)",
    member: false,
    combat: 13,
    hp: 13,
  },
  {
    monster: "Crawling hand (lvl12)",
    member: false,
    combat: 12,
    hp: 19,
  },
  {
    monster: "Minotaur",
    member: false,
    combat: 12,
    hp: 10,
  },
  {
    monster: "Icefiend",
    member: true,
    combat: 13,
    hp: 15,
  },
  {
    monster: "Giant frog",
    member: false,
    combat: 13,
    hp: 23,
  },
  {
    monster: "Rock Crab",
    member: true,
    combat: 13,
    hp: 50,
  },
  {
    monster: "Skeleton (The Restless Ghost)",
    member: false,
    combat: 13,
    hp: 18,
  },
  {
    monster: "Giant mosquito",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Hazeel Cultist",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Mourner (boss)",
    member: true,
    combat: 13,
    hp: 19,
  },
  {
    monster: "Summoned Zombie",
    member: true,
    combat: 13,
    hp: 22,
  },
  {
    monster: "Alomone",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Kebbit",
    member: true,
    combat: 13,
    hp: 50,
  },
  {
    monster: "Air wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Earth wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Water wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Fire wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Flawed Golem",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Zombie (lvl13)",
    member: false,
    combat: 13,
    hp: 22,
  },
  {
    monster: "Disciple of Iban",
    member: true,
    combat: 13,
    hp: 20,
  },
  {
    monster: "Clivet",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Large mosquito",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Chaos druid",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Thief (Monk's Friend)",
    member: true,
    combat: 14,
    hp: 17,
  },
  {
    monster: "River troll",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Wolf (lvl14)",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Scorpion (lvl14)",
    member: true,
    combat: 14,
    hp: 17,
  },
  {
    monster: "Rock Golem (lvl14)",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Imp Champion",
    member: true,
    combat: 14,
    hp: 40,
  },
  {
    monster: "Woman (West Ardougne)",
    member: true,
    combat: 14,
    hp: 23,
  },
  {
    monster: "Tree spirit",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Lucien",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Scorpia's offspring",
    member: true,
    combat: 15,
    hp: 2,
  },
  {
    monster: "Sand Crab",
    member: true,
    combat: 15,
    hp: 60,
  },
  {
    monster: "Rogue (lvl15)",
    member: true,
    combat: 15,
    hp: 17,
  },
  {
    monster: "Revenant goblin",
    member: true,
    combat: 15,
    hp: 14,
  },
  {
    monster: "Stag",
    member: true,
    combat: 15,
    hp: 19,
  },
  {
    monster: "Bear Cub",
    member: true,
    combat: 15,
    hp: 20,
  },
  {
    monster: "Forester (Woodcutting Guild)",
    member: true,
    combat: 15,
    hp: 17,
  },
  {
    monster: "Bark Blamish Snail",
    member: true,
    combat: 15,
    hp: 22,
  },
  {
    monster: "Barbarian (lvl15)",
    member: true,
    combat: 15,
    hp: 22,
  },
  {
    monster: "Unicorn",
    member: false,
    combat: 15,
    hp: 19,
  },
  {
    monster: "Thief Varrock",
    member: false,
    combat: 16,
    hp: 17,
  },
  {
    monster: "Skeleton Mage (lvl16)",
    member: true,
    combat: 16,
    hp: 17,
  },
  {
    monster: "Goblin (Vault of War)",
    member: false,
    combat: 16,
    hp: 22,
  },
  {
    monster: "Tormented Soul",
    member: true,
    combat: 16,
    hp: 20,
  },
  {
    monster: "Barbarian (lvl17)",
    member: false,
    combat: 16,
    hp: 20,
  },
  {
    monster: "Monk of Zamorak",
    member: false,
    combat: 17,
    hp: 10,
  },
  {
    monster: "Mosquito swarm (lvl17)",
    member: true,
    combat: 17,
    hp: 9,
  },
  {
    monster: "Soulless",
    member: true,
    combat: 18,
    hp: 24,
  },
  {
    monster: "Zombie (lvl18)",
    member: false,
    combat: 18,
    hp: 24,
  },
  {
    monster: "H.A.M. Guard (lvl18)",
    member: true,
    combat: 18,
    hp: 20,
  },
  {
    monster: "Icefiend",
    member: true,
    combat: 18,
    hp: 20,
  },
  {
    monster: "Locust",
    member: true,
    combat: 18,
    hp: 27,
  },
  {
    monster: "Pirate Guard",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Ghost (lvl19)",
    member: false,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Guard (Hosidius)",
    member: true,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Fox",
    member: true,
    combat: 19,
    hp: 30,
  },
  {
    monster: "Zamorak crafter",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Black bear",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Tower Archer",
    member: true,
    combat: 19,
    hp: 30,
  },
  {
    monster: "Witch's experiment Skavid",
    member: true,
    combat: 19,
    hp: 21,
  },
  {
    monster: "Suit of armour",
    member: true,
    combat: 19,
    hp: 29,
  },
  {
    monster: "Guard (Doric's hut)",
    member: false,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Guard Falador",
    member: false,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Khazard trooper",
    member: true,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Scarred imp",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Hoop Snake",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Newtroost",
    member: true,
    combat: 19,
    hp: 18,
  },
  {
    monster: "Bruise Blamish Snail Round",
    member: true,
    combat: 20,
    hp: 12,
  },
  {
    monster: "Bruise Blamish Snail Pointed",
    member: true,
    combat: 20,
    hp: 15,
  },
  {
    monster: "Blood Blamish Snail Round",
    member: true,
    combat: 20,
    hp: 13,
  },
  {
    monster: "Blood Blamish Snail Pointed",
    member: true,
    combat: 20,
    hp: 10,
  },
  {
    monster: "Market Guard (Draynor)",
    member: true,
    combat: 20,
    hp: 22,
  },
  {
    monster: "Mosquito swarm (lvl20)",
    member: true,
    combat: 20,
    hp: 15,
  },
  {
    monster: "Dwarf",
    member: false,
    combat: 20,
    hp: 26,
  },
  {
    monster: "Forgotten Soul",
    member: true,
    combat: 20,
    hp: 50,
  },
  {
    monster: "Poison Scorpion",
    member: true,
    combat: 20,
    hp: 23,
  },
  {
    monster: "Sir Leye",
    member: true,
    combat: 20,
    hp: 20,
  },
  {
    monster: "Fortress Guard",
    member: false,
    combat: 20,
    hp: 22,
  },
  {
    monster: "Invrigar the Necromancer",
    member: true,
    combat: 20,
    hp: 24,
  },
  // Level 21 to 20
  {
    monster: "Thief",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Grizzly bear",
    member: false,
    combat: 21,
    hp: 27,
  },
  {
    monster: "Poltenip",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Penance Ranger (wave1)",
    member: true,
    combat: 21,
    hp: 20,
  },
  {
    monster: "Skeleton (lvl21)",
    member: false,
    combat: 21,
    hp: 24,
  },
  {
    monster: "Jackal",
    member: true,
    combat: 21,
    hp: 27,
  },
  {
    monster: "Radat",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Lynx (lvl21)",
    member: true,
    combat: 21,
    hp: 25,
  },
  {
    monster: "Lynx Tamer",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Soldier (Shayzien)",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Crab (lvl21)",
    member: true,
    combat: 21,
    hp: 17,
  },
  {
    monster: "Tarik (Nardah)",
    member: true,
    combat: 21,
    hp: 22,
  },
  {
    monster: "Guard Bandit",
    member: false,
    combat: 22,
    hp: 27,
  },
  {
    monster: "Skeleton (Melzar's Maze)",
    member: false,
    combat: 22,
    hp: 29,
  },
  {
    monster: "Tz-Kek (lvl22)",
    member: true,
    combat: 22,
    hp: 10,
  },
  {
    monster: "Skeleton guard",
    member: true,
    combat: 22,
    hp: 29,
  },
  {
    monster: "Guard (Hosidius)",
    member: true,
    combat: 22,
    hp: 22,
  },
  {
    monster: "H.A.M. Guard (lvl22)",
    member: true,
    combat: 22,
    hp: 30,
  },
  {
    monster: "Tz-Kih",
    member: true,
    combat: 22,
    hp: 1,
  },
  {
    monster: "Shantay Guard",
    member: false,
    combat: 22,
    hp: 32,
  },
  {
    monster: "Monk of Zamorak (lvl22)",
    member: false,
    combat: 22,
    hp: 20,
  },
  {
    monster: "Yak",
    member: true,
    combat: 22,
    hp: 50,
  },
  {
    monster: "Guard (Death to the Dorgeshuun)",
    member: true,
    combat: 22,
    hp: 30,
  },
  {
    monster: "Splatter (lvl22)",
    member: true,
    combat: 22,
    hp: 13,
  },
  {
    monster: "Dark wizard (lvl22)",
    member: true,
    combat: 22,
    hp: 25,
  },
  {
    monster: "Bandit (Shayzien)",
    member: true,
    combat: 22,
    hp: 27,
  },
  {
    monster: "Bandit (lvl22)",
    member: false,
    combat: 22,
    hp: 27,
  },
  {
    monster: "Black unicorn Foal",
    member: true,
    combat: 22,
    hp: 25,
  },
  {
    monster: "Crystalline Spider",
    member: true,
    combat: 22,
    hp: 12,
  },
  {
    monster: "Grip",
    member: true,
    combat: 22,
    hp: 25,
  },
  {
    monster: "Dark wizard (lvl23)",
    member: true,
    combat: 23,
    hp: 25,
  },
  {
    monster: "Weaponsmaster",
    member: false,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Monk of Zamorak",
    member: false,
    combat: 23,
    hp: 16,
  },
  {
    monster: "Crab (lvl23)",
    member: false,
    combat: 23,
    hp: 19,
  },
  {
    monster: "Foreman",
    member: true,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Cave crawler",
    member: true,
    combat: 23,
    hp: 22,
  },
  {
    monster: "Animated Iron Armour",
    member: true,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Cave slime",
    member: true,
    combat: 23,
    hp: 25,
  },
  {
    monster: "Khazard Guard",
    member: true,
    combat: 23,
    hp: 25,
  },
  {
    monster: "Pirate Port Sarim",
    member: false,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Zombie (Temple Trekking)",
    member: true,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Banshee",
    member: true,
    combat: 23,
    hp: 22,
  },
  {
    monster: "Gnome guard",
    member: true,
    combat: 23,
    hp: 31,
  },
  {
    monster: "Goat",
    member: true,
    combat: 23,
    hp: 21,
  },
  {
    monster: "Pirate Pirate's Cove",
    member: true,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Pirate Port Piscarilius",
    member: true,
    combat: 23,
    hp: 20,
  },
  {
    monster: "Guard (Cave goblin)",
    member: true,
    combat: 24,
    hp: 26,
  },
  {
    monster: "Zombie (lvl24)",
    member: false,
    combat: 24,
    hp: 30,
  },
  {
    monster: "Imre",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Irina",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Crystalline Rat",
    member: true,
    combat: 24,
    hp: 14,
  },
  {
    monster: "Lev",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Yuri",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Nikolai",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Big frog (lvl24)",
    member: true,
    combat: 24,
    hp: 25,
  },
  {
    monster: "Boris",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Ksenia",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Milla",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Nikita",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Liliya",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Zoja",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Cave goblin gaurd (lvl24)",
    member: true,
    combat: 24,
    hp: 26,
  },
  {
    monster: "Lynx (lvl24)",
    member: true,
    combat: 24,
    hp: 26,
  },
  {
    monster: "Joseph",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Yadviga",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Eduard",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Warrior (Thieving)",
    member: false,
    combat: 24,
    hp: 20,
  },
  {
    monster: "Swamp frog",
    member: true,
    combat: 24,
    hp: 25,
  },
  {
    monster: "Ghost (Grave of Scorpius)",
    member: true,
    combat: 24,
    hp: 20,
  },
  {
    monster: "Spider Stronghold of Security",
    member: false,
    combat: 24,
    hp: 22,
  },
  {
    monster: "Zombie (Melzar's Maze)",
    member: false,
    combat: 24,
    hp: 30,
  },
  {
    monster: "Alexis",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Georgy",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Sofiya",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Vera",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Goblin Champion",
    member: true,
    combat: 24,
    hp: 32,
  },
  {
    monster: "Snake (Ape Atoll)",
    member: true,
    combat: 24,
    hp: 36,
  },
  {
    monster: "Svetlana",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Galina",
    member: true,
    combat: 24,
    hp: 60,
  },
  {
    monster: "Experiment Level 25 (spider)",
    member: true,
    combat: 24,
    hp: 100,
  },
  {
    monster: "Experiment Level 25 (sheep)",
    member: true,
    combat: 24,
    hp: 100,
  },
  {
    monster: "Penance Ranger (wave2)",
    member: true,
    combat: 25,
    hp: 28,
  },
  {
    monster: "Camp dweller",
    member: true,
    combat: 25,
    hp: 25,
  },
  {
    monster: "Ancient Guardian",
    member: false,
    combat: 25,
    hp: 40,
  },
  {
    monster: "Zombie (Entrana Dungeon)",
    member: true,
    combat: 25,
    hp: 30,
  },
  {
    monster: "Skeleton (lvl25)",
    member: false,
    combat: 25,
    hp: 17,
  },
  {
    monster: "Skeleton (Forthos Ruin)",
    member: true,
    combat: 25,
    hp: 17,
  },
  {
    monster: "Wolf (lvl25)",
    member: true,
    combat: 25,
    hp: 34,
  },
  {
    monster: "Unicow",
    member: true,
    combat: 25,
    hp: 24,
  },
  {
    monster: "Ammonite Crab",
    member: true,
    combat: 25,
    hp: 100,
  },
  {
    monster: "White wolf (lvl25)",
    member: true,
    combat: 25,
    hp: 34,
  },
  {
    monster: "Black Guard (lvl25)",
    member: false,
    combat: 25,
    hp: 30,
  },
  {
    monster: "Jail guard",
    member: false,
    combat: 26,
    hp: 32,
  },
  {
    monster: "Cave goblin guard (lvl26)",
    member: true,
    combat: 26,
    hp: 26,
  },
  {
    monster: "Head Thief",
    member: true,
    combat: 26,
    hp: 37,
  },
  {
    monster: "Pirate Asgarnian Ice Dungeon",
    member: false,
    combat: 26,
    hp: 23,
  },
  {
    monster: "Giant rat (lvl26)",
    member: false,
    combat: 26,
    hp: 25,
  },
  {
    monster: "Necromancer (Necromancer Tower)",
    member: true,
    combat: 26,
    hp: 40,
  },
  {
    monster: "Desert Wolf",
    member: true,
    combat: 27,
    hp: 40,
  },
  {
    monster: "Giant bat",
    member: true,
    combat: 27,
    hp: 32,
  },
  {
    monster: "Giant spider (lvl27)",
    member: false,
    combat: 27,
    hp: 32,
  },
  {
    monster: "Black unicorn",
    member: true,
    combat: 27,
    hp: 29,
  },
  {
    monster: "Minotaur (lvl27)",
    member: false,
    combat: 27,
    hp: 22,
  },
  {
    monster: "Delrith",
    member: false,
    combat: 27,
    hp: 7,
  },
  {
    monster: "Knight of Ardougne (Song of the Elves)",
    member: true,
    combat: 27,
    hp: 40,
  },
  {
    monster: "Terrorbird",
    member: true,
    combat: 28,
    hp: 34,
  },
  {
    monster: "Tower guard",
    member: true,
    combat: 28,
    hp: 22,
  },
  {
    monster: "Hobgoblin",
    member: false,
    combat: 28,
    hp: 29,
  },
  {
    monster: "Hobgoblin (lvl42)",
    member: false,
    combat: 42,
    hp: 49,
  },
  {
    monster: "Hill Giant",
    member: false,
    combat: 28,
    hp: 35,
  },
  {
    monster: "Soldier (Yanille)",
    member: true,
    combat: 28,
    hp: 22,
  },
  {
    monster: "Flesh Crawler (lvl28)",
    member: false,
    combat: 28,
    hp: 25,
  },
  {
    monster: "Hill Giant (Dark)",
    member: true,
    combat: 28,
    hp: 35,
  },
  {
    monster: "Kalphite Worker",
    member: true,
    combat: 28,
    hp: 40,
  },
  {
    monster: "Pit Scorpion",
    member: true,
    combat: 28,
    hp: 32,
  },
  {
    monster: "Ghost (lvl29)",
    member: false,
    combat: 29,
    hp: 27,
  },
  {
    monster: "Gunthor the brave",
    member: false,
    combat: 29,
    hp: 35,
  },
  {
    monster: "Skoblin",
    member: true,
    combat: 29,
    hp: 30,
  },
  {
    monster: "River troll (lvl29)",
    member: true,
    combat: 29,
    hp: 40,
  },
  {
    monster: "Rockslug",
    member: true,
    combat: 29,
    hp: 27,
  },
  {
    monster: "Tree spirit",
    member: true,
    combat: 29,
    hp: 40,
  },
  {
    monster: "Rock Golem (lvl29)",
    member: true,
    combat: 29,
    hp: 40,
  },
  {
    monster: "Witch's experiment Spider",
    member: true,
    combat: 30,
    hp: 31,
  },
  {
    monster: "Abyssal antibody",
    member: true,
    combat: 30,
    hp: 50,
  },
  {
    monster: "Trapped Soul",
    member: true,
    combat: 30,
    hp: 30,
  },
  {
    monster: "H.A.M. Archer",
    member: true,
    combat: 30,
    hp: 35,
  },
  {
    monster: "H.A.M. Mage",
    member: true,
    combat: 30,
    hp: 35,
  },
  {
    monster: "Ghast (lvl30)",
    member: true,
    combat: 30,
    hp: 45,
  },
  {
    monster: "Afflicted (lvl30)",
    member: true,
    combat: 30,
    hp: 24,
  },
  {
    monster: "Undead Lumberjack (lvl30)",
    member: true,
    combat: 30,
    hp: 10,
  },
  {
    monster: "Mind Golem",
    member: false,
    combat: 30,
    hp: 40,
  },
  {
    monster: "Monk of Zamorak",
    member: false,
    combat: 30,
    hp: 25,
  },
  {
    monster: "Temple Guardian",
    member: true,
    combat: 30,
    hp: 45,
  },
  {
    monster: "Penance Fighter (wave1)",
    member: true,
    combat: 30,
    hp: 28,
  },
  {
    monster: "Mudskipper (lvl30)",
    member: true,
    combat: 30,
    hp: 20,
  },
  {
    monster: "Zombie (lvl30)",
    member: false,
    combat: 30,
    hp: 30,
  },
  // Level 31 to 40
  {
    monster: "Camp dweller (lvl31)",
    member: true,
    combat: 31,
    hp: 30,
  },
  {
    monster: "Poison spider (lvl31)",
    member: true,
    combat: 31,
    hp: 25,
  },
  {
    monster: "Vulture",
    member: true,
    combat: 31,
    hp: 10,
  },
  {
    monster: "Mudskipper (lvl31)",
    member: true,
    combat: 31,
    hp: 20,
  },
  {
    monster: "Mounted terrorbird gnome (lvl31)",
    member: true,
    combat: 31,
    hp: 36,
  },
  {
    monster: "Jal-Nib",
    member: true,
    combat: 32,
    hp: 10,
  },
  {
    monster: "Outlaw",
    member: false,
    combat: 32,
    hp: 20,
  },
  {
    monster: "Snothead",
    member: true,
    combat: 32,
    hp: 50,
  },
  {
    monster: "King Scorpion",
    member: false,
    combat: 32,
    hp: 30,
  },
  {
    monster: "Corrupted Spider",
    member: true,
    combat: 32,
    hp: 12,
  },
  {
    monster: "Penance Ranger (wave3)",
    member: true,
    combat: 32,
    hp: 29,
  },
  {
    monster: "Penance Fighter (wave2)",
    member: true,
    combat: 32,
    hp: 29,
  },
  {
    monster: "Abyssal leech (lvl32)",
    member: true,
    combat: 32,
    hp: 50,
  },
  {
    monster: "Abyssal leech (lvl46)",
    member: true,
    combat: 46,
    hp: 3,
  },
  {
    monster: "Giant lobster (Ghosts Ahoy)",
    member: true,
    combat: 32,
    hp: 32,
  },
  {
    monster: "Tribesman",
    member: true,
    combat: 32,
    hp: 39,
  },
  {
    monster: "Tribeswoman",
    member: true,
    combat: 32,
    hp: 39,
  },
  {
    monster: "Afflicted (lvl32)",
    member: true,
    combat: 32,
    hp: 26,
  },
  {
    monster: "Black Knight (Wanted!)",
    member: true,
    combat: 32,
    hp: 42,
  },
  {
    monster: "Black Knight",
    member: false,
    combat: 32,
    hp: 42,
  },
  {
    monster: "Defiler (lvl33)",
    member: true,
    combat: 33,
    hp: 27,
  },
  {
    monster: "Grizzly bear cub (lvl33)",
    member: true,
    combat: 33,
    hp: 35,
  },
  {
    monster: "Druid",
    member: true,
    combat: 33,
    hp: 30,
  },
  {
    monster: "Splatter (lvl33)",
    member: true,
    combat: 33,
    hp: 23,
  },
  {
    monster: "Black knight (Port Sarim Jail)",
    member: false,
    combat: 33,
    hp: 42,
  },
  {
    monster: "Crystalline Bat",
    member: true,
    combat: 33,
    hp: 14,
  },
  {
    monster: "Billy Goat",
    member: true,
    combat: 33,
    hp: 28,
  },
  {
    monster: "Torcher (lvl33)",
    member: true,
    combat: 33,
    hp: 18,
  },
  {
    monster: "Watchman",
    member: true,
    combat: 33,
    hp: 22,
  },
  {
    monster: "Undead Zealot",
    member: true,
    combat: 34,
    hp: 28,
  },
  {
    monster: "Radiant sanguisphera",
    member: true,
    combat: 34,
    hp: 20,
  },
  {
    monster: "Water elemental",
    member: true,
    combat: 34,
    hp: 30,
  },
  {
    monster: "Tower Archer",
    member: true,
    combat: 34,
    hp: 50,
  },
  {
    monster: "Spinolyp",
    member: true,
    combat: 34,
    hp: 100,
  },
  {
    monster: "Speedy Keith",
    member: false,
    combat: 34,
    hp: 37,
  },
  {
    monster: "Count Draynor",
    member: false,
    combat: 34,
    hp: 35,
  },
  {
    monster: "Deadly red spider",
    member: false,
    combat: 34,
    hp: 35,
  },
  {
    monster: "Donny the lad",
    member: false,
    combat: 34,
    hp: 37,
  },
  {
    monster: "Air elemental",
    member: true,
    combat: 34,
    hp: 30,
  },
  {
    monster: "Black Heather",
    member: true,
    combat: 34,
    hp: 30,
  },
  {
    monster: "Corrupted Rat",
    member: true,
    combat: 34,
    hp: 30,
  },
  {
    monster: "Afflicted (lvl34)",
    member: true,
    combat: 34,
    hp: 28,
  },
  {
    monster: "Crimson sanguisphera",
    member: true,
    combat: 34,
    hp: 20,
  },
  {
    monster: "Snake (Mos Le'Harmless)",
    member: true,
    combat: 35,
    hp: 25,
  },
  {
    monster: "Earth elemental",
    member: true,
    combat: 35,
    hp: 35,
  },
  {
    monster: "Gadderanks",
    member: true,
    combat: 35,
    hp: 20,
  },
  {
    monster: "Spider (Ungael)",
    member: true,
    combat: 35,
    hp: 4,
  },
  {
    monster: "Earth elemental",
    member: true,
    combat: 35,
    hp: 35,
  },
  {
    monster: "Bush snake",
    member: true,
    combat: 35,
    hp: 25,
  },
  {
    monster: "Ithoi the Navigator",
    member: false,
    combat: 35,
    hp: 55,
  },
  {
    monster: "Undead Lumberjack (lvl35)",
    member: true,
    combat: 35,
    hp: 12,
  },
  {
    monster: "Flesh Crawler (lvl35)",
    member: false,
    combat: 35,
    hp: 25,
  },
  {
    monster: "Ithoi the Navigator",
    member: false,
    combat: 35,
    hp: 55,
  },
  {
    monster: "Fire elemental",
    member: true,
    combat: 35,
    hp: 30,
  },
  {
    monster: "Ravager (lvl36)",
    member: true,
    combat: 36,
    hp: 23,
  },
  {
    monster: "White Knight (Burthorpe)",
    member: true,
    combat: 36,
    hp: 52,
  },
  {
    monster: "Spinner (lvl36)",
    member: true,
    combat: 36,
    hp: 33,
  },
  {
    monster: "Grizzly bear cub (lvl36)",
    member: true,
    combat: 36,
    hp: 35,
  },
  {
    monster: "Sand Snake",
    member: true,
    combat: 36,
    hp: 60,
  },
  {
    monster: "White Knight",
    member: false,
    combat: 36,
    hp: 52,
  },
  {
    monster: "White Knight (lvl38)",
    member: false,
    combat: 38,
    hp: 52,
  },
  {
    monster: "Jungle spider (Ape Atoll)",
    member: true,
    combat: 37,
    hp: 35,
  },
  {
    monster: "Penance Fighter (wave3)",
    member: true,
    combat: 37,
    hp: 32,
  },
  {
    monster: "Jake",
    member: true,
    combat: 37,
    hp: 50,
  },
  {
    monster: "Sourhog (A Porcine of Interest)",
    member: true,
    combat: 37,
    hp: 40,
  },
  {
    monster: "Archer (Ardougne)",
    member: true,
    combat: 37,
    hp: 50,
  },
  {
    monster: "Guard (Burthorpe)",
    member: true,
    combat: 37,
    hp: 40,
  },
  {
    monster: "Growthling",
    member: false,
    combat: 37,
    hp: 10,
  },
  {
    monster: "Wilson",
    member: false,
    combat: 37,
    hp: 50,
  },
  {
    monster: "Guard (Burthorpe)",
    member: true,
    combat: 37,
    hp: 40,
  },
  {
    monster: "Afflicted (lvl37)",
    member: true,
    combat: 37,
    hp: 30,
  },
  {
    monster: "Sourhog",
    member: true,
    combat: 37,
    hp: 30,
  },
  {
    monster: "Cave lizard",
    member: true,
    combat: 37,
    hp: 20,
  },
  {
    monster: "Cockatrice",
    member: true,
    combat: 37,
    hp: 37,
  },
  {
    monster: "Scorpion",
    member: false,
    combat: 37,
    hp: 37,
  },
  {
    monster: "Chaos druid warrior",
    member: true,
    combat: 37,
    hp: 40,
  },
  {
    monster: "Dark warrior (lvl37)",
    member: true,
    combat: 37,
    hp: 40,
  },
  {
    monster: "Renegade knight",
    member: true,
    combat: 37,
    hp: 48,
  },
  {
    monster: "Palmer",
    member: true,
    combat: 37,
    hp: 50,
  },
  {
    monster: "Guard (Ranging Guild)",
    member: true,
    combat: 37,
    hp: 50,
  },
  {
    monster: "White wolf (lvl38)",
    member: true,
    combat: 37,
    hp: 44,
  },
  {
    monster: "Penance Ranger (wave4)",
    member: true,
    combat: 37,
    hp: 44,
  },
  {
    monster: "Scorpion (lvl38)",
    member: true,
    combat: 38,
    hp: 15,
  },
  {
    monster: "Shifter (lvl38)",
    member: true,
    combat: 38,
    hp: 23,
  },
  {
    monster: "Colonel Radick",
    member: true,
    combat: 38,
    hp: 65,
  },
  {
    monster: "Lesser demon (lvl39)",
    member: true,
    combat: 39,
    hp: 40,
  },
  {
    monster: "Soldier (tier 1)",
    member: true,
    combat: 39,
    hp: 50,
  },
  {
    monster: "Blessed spider",
    member: true,
    combat: 39,
    hp: 32,
  },
  {
    monster: "Sir Mordred",
    member: true,
    combat: 39,
    hp: 38,
  },
  {
    monster: "Zombie (Zogre Flesh Eaters)",
    member: true,
    combat: 39,
    hp: 50,
  },
  {
    monster: "Loar Shade",
    member: true,
    combat: 40,
    hp: 38,
  },
  {
    monster: "Skeleton fremennik (lvl40)",
    member: true,
    combat: 40,
    hp: 25,
  },
  {
    monster: "Angry bear (lvl40)",
    member: true,
    combat: 40,
    hp: 200,
  },
  {
    monster: "Skeleton (lvl40)",
    member: true,
    combat: 40,
    hp: 26,
  },
  {
    monster: "Zombie (lvl40)",
    member: true,
    combat: 40,
    hp: 38,
  },
  {
    monster: "Skeleton Champion",
    member: true,
    combat: 40,
    hp: 58,
  },
  {
    monster: "Hopeless creature (lvl40)",
    member: true,
    combat: 40,
    hp: 25,
  },
  {
    monster: "Undead Lumberjack (lvl40)",
    member: true,
    combat: 40,
    hp: 12,
  },
  {
    monster: "Undead Lumberjack (lvl45)",
    member: true,
    combat: 45,
    hp: 13,
  },
  {
    monster: "Loar Shade",
    member: true,
    combat: 40,
    hp: 38,
  },
  // Level 41 to 50
  {
    monster: "Abyssal leech",
    member: true,
    combat: 41,
    hp: 10,
  },
  {
    monster: "Bandit (Pollnivneach)",
    member: true,
    combat: 41,
    hp: 30,
  },
  {
    monster: "Flesh Crawler (lvl41)",
    member: false,
    combat: 41,
    hp: 25,
  },
  {
    monster: "Lizard",
    member: true,
    combat: 42,
    hp: 40,
  },
  {
    monster: "Magic axe",
    member: true,
    combat: 42,
    hp: 44,
  },
  {
    monster: "Fear reaper (lvl42)",
    member: true,
    combat: 42,
    hp: 25,
  },
  {
    monster: "Grizzly bear (lvl42)",
    member: true,
    combat: 42,
    hp: 35,
  },
  {
    monster: "Dagannoth spawn",
    member: true,
    combat: 42,
    hp: 35,
  },
  {
    monster: "Moss giant (lvl42)",
    member: false,
    combat: 42,
    hp: 60,
  },
  {
    monster: "Ghoul",
    member: true,
    combat: 42,
    hp: 50,
  },
  {
    monster: "Goblin guard",
    member: true,
    combat: 42,
    hp: 43,
  },
  {
    monster: "Penance Fighter (wave4)",
    member: true,
    combat: 42,
    hp: 37,
  },
  {
    monster: "Witch's experiment Bear",
    member: true,
    combat: 42,
    hp: 41,
  },
  {
    monster: "Skeleton (lvl42)",
    member: true,
    combat: 42,
    hp: 40,
  },
  {
    monster: "Ugthanki",
    member: true,
    combat: 42,
    hp: 45,
  },
  {
    monster: "Spidine",
    member: true,
    combat: 42,
    hp: 35,
  },
  {
    monster: "Archer (Burthorpe)",
    member: true,
    combat: 42,
    hp: 35,
  },
  {
    monster: "Zombie (lvl42)",
    member: true,
    combat: 42,
    hp: 40,
  },
  {
    monster: "Skeletal miner",
    member: true,
    combat: 42,
    hp: 39,
  },
  {
    monster: "Penance Ranger (wave5)",
    member: true,
    combat: 43,
    hp: 41,
  },
  {
    monster: "Confusion beast (lvl43)",
    member: true,
    combat: 43,
    hp: 28,
  },
  {
    monster: "Crypt rat",
    member: true,
    combat: 43,
    hp: 35,
  },
  {
    monster: "Guardian of Armadyl (female)",
    member: true,
    combat: 43,
    hp: 40,
  },
  {
    monster: "Guardian of Armadyl (male)",
    member: true,
    combat: 45,
    hp: 50,
  },
  {
    monster: "Melzar the Mad",
    member: false,
    combat: 43,
    hp: 44,
  },
  {
    monster: "Pyrefiend",
    member: false,
    combat: 43,
    hp: 45,
  },
  {
    monster: "Zogre",
    member: false,
    combat: 44,
    hp: 71,
  },
  {
    monster: "Guard dog",
    member: false,
    combat: 44,
    hp: 49,
  },
  {
    monster: "Skogre",
    member: false,
    combat: 44,
    hp: 71,
  },
  {
    monster: "Splatter (lvl44)",
    member: false,
    combat: 44,
    hp: 33,
  },
  {
    monster: "Jungle spider",
    member: false,
    combat: 44,
    hp: 50,
  },
  {
    monster: "Khazard Scorpion",
    member: false,
    combat: 44,
    hp: 40,
  },
  {
    monster: "Guard dog (Construction)",
    member: false,
    combat: 44,
    hp: 49,
  },
  {
    monster: "Dwarf gang member",
    member: false,
    combat: 44,
    hp: 40,
  },
  {
    monster: "Zombie (lvl44)",
    member: false,
    combat: 44,
    hp: 40,
  },
  {
    monster: "Baby tanglefoot",
    member: true,
    combat: 45,
    hp: 40,
  },
  {
    monster: "Vampyre Juvenile",
    member: true,
    combat: 45,
    hp: 60,
  },
  {
    monster: "Guard (Desert Mining Camp)",
    member: true,
    combat: 45,
    hp: 60,
  },
  {
    monster: "Mercenary",
    member: true,
    combat: 45,
    hp: 60,
  },
  {
    monster: "Skeleton (lvl45)",
    member: false,
    combat: 45,
    hp: 60,
  },
  {
    monster: "Angry unicorn (lvl45)",
    member: true,
    combat: 45,
    hp: 200,
  },
  {
    monster: "Tz-Kek (lvl45)",
    member: true,
    combat: 45,
    hp: 20,
  },
  {
    monster: "Crushing hand",
    member: true,
    combat: 45,
    hp: 55,
  },
  {
    monster: "Angry giant rat (lvl45)",
    member: true,
    combat: 45,
    hp: 200,
  },
  {
    monster: "Gangster (lvl45)",
    member: true,
    combat: 45,
    hp: 40,
  },
  {
    monster: "Monk of Zamorak (lvl45)",
    member: false,
    combat: 45,
    hp: 40,
  },
  {
    monster: "Angry goblin (lvl45)",
    member: true,
    combat: 45,
    hp: 200,
  },
  {
    monster: "Giant lobster",
    member: true,
    combat: 45,
    hp: 50,
  },
  {
    monster: "Knight of Ardougne",
    member: true,
    combat: 46,
    hp: 52,
  },
  {
    monster: "Animated Steel Armour",
    member: true,
    combat: 46,
    hp: 42,
  },
  {
    monster: "Swordchick",
    member: true,
    combat: 46,
    hp: 35,
  },
  {
    monster: "Tolna",
    member: true,
    combat: 46,
    hp: 37,
  },
  {
    monster: "Death spawn",
    member: true,
    combat: 46,
    hp: 60,
  },
  {
    monster: "Corrupt Lizardman",
    member: true,
    combat: 46,
    hp: 50,
  },
  {
    monster: "Oomlie bird",
    member: true,
    combat: 46,
    hp: 40,
  },
  {
    monster: "Harpie Bug Swarm",
    member: true,
    combat: 46,
    hp: 25,
  },
  {
    monster: "Forgotten Soul (lvl46)",
    member: true,
    combat: 46,
    hp: 50,
  },
  {
    monster: "Penance Fighter (wave5)",
    member: true,
    combat: 47,
    hp: 38,
  },
  {
    monster: "Scorpia's guardian",
    member: true,
    combat: 47,
    hp: 70,
  },
  {
    monster: "Mercenary Captain",
    member: true,
    combat: 47,
    hp: 80,
  },
  {
    monster: "Phantom Hand",
    member: true,
    combat: 47,
    hp: 12,
  },
  {
    monster: "Angry giant rat (lvl47)",
    member: true,
    combat: 47,
    hp: 50,
  },
  {
    monster: "Angry bear (lvl47)",
    member: true,
    combat: 47,
    hp: 50,
  },
  {
    monster: "Hobgoblin (GWD)",
    member: true,
    combat: 47,
    hp: 52,
  },
  {
    monster: "Zombie (lvl47)",
    member: true,
    combat: 47,
    hp: 52,
  },
  {
    monster: "Jailer",
    member: true,
    combat: 47,
    hp: 47,
  },
  {
    monster: "Angry goblin (lvl47)",
    member: true,
    combat: 47,
    hp: 50,
  },
  {
    monster: "Witch's experiment Skavid (hard)",
    member: true,
    combat: 47,
    hp: 63,
  },
  {
    monster: "Angry unicorn (lvl47)",
    member: true,
    combat: 47,
    hp: 50,
  },
  {
    monster: "King Roald",
    member: true,
    combat: 47,
    hp: 75,
  },
  {
    monster: "Baby blue dragon",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Pyrefiend (GWD)",
    member: true,
    combat: 48,
    hp: 48,
  },
  {
    monster: "Poison spider (Escape Caves)",
    member: true,
    combat: 48,
    hp: 73,
  },
  {
    monster: "Soldier (Burthorpe)",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Shadow warrior",
    member: true,
    combat: 48,
    hp: 67,
  },
  {
    monster: "Soldier (tier 2)",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Khazard commander",
    member: true,
    combat: 48,
    hp: 22,
  },
  {
    monster: "Moss giant (lvl48)",
    member: true,
    combat: 48,
    hp: 85,
  },
  {
    monster: "Jennella",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Market Guard",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Husk",
    member: true,
    combat: 48,
    hp: 20,
  },
  {
    monster: "Chaos dwarf",
    member: false,
    combat: 48,
    hp: 61,
  },
  {
    monster: "Baby red dragon",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Lensa",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Lanzig",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Borrokar",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Dwarf gang member (lvl48)",
    member: true,
    combat: 48,
    hp: 25,
  },
  {
    monster: "Baby green dragon",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Black Guard (lvl48)",
    member: true,
    combat: 48,
    hp: 40,
  },
  {
    monster: "Freidir",
    member: true,
    combat: 48,
    hp: 50,
  },
  {
    monster: "Corrupted Bat",
    member: true,
    combat: 48,
    hp: 14,
  },
  {
    monster: "Crystalline Unicorn",
    member: true,
    combat: 48,
    hp: 44,
  },
  {
    monster: "Tree spirit (lvl49)",
    member: true,
    combat: 48,
    hp: 60,
  },
  {
    monster: "Catablepon",
    member: false,
    combat: 49,
    hp: 40,
  },
  {
    monster: "Wall beast",
    member: true,
    combat: 49,
    hp: 105,
  },
  {
    monster: "Fever spider",
    member: true,
    combat: 49,
    hp: 40,
  },
  {
    monster: "Tower Archer",
    member: true,
    combat: 49,
    hp: 70,
  },
  {
    monster: "Dwarf gang member (lvl49)",
    member: true,
    combat: 49,
    hp: 25,
  },
  {
    monster: "Rock Golem (lvl49)",
    member: true,
    combat: 49,
    hp: 60,
  },
  {
    monster: "River troll (lvl49)",
    member: true,
    combat: 49,
    hp: 60,
  },
  {
    monster: "Mounted terrorbird gnome",
    member: true,
    combat: 49,
    hp: 55,
  },
  {
    monster: "Paladin (lvl49)",
    member: true,
    combat: 49,
    hp: 55,
  },
  {
    monster: "Torcher (lvl49)",
    member: true,
    combat: 49,
    hp: 30,
  },
  {
    monster: "Gangster (lvl50)",
    member: true,
    combat: 50,
    hp: 50,
  },
  {
    monster: "Possessed pickaxe",
    member: true,
    combat: 50,
    hp: 40,
  },
  {
    monster: "Giant spider (lvl50)",
    member: false,
    combat: 50,
    hp: 50,
  },
  {
    monster: "Defiler (lvl50)",
    member: true,
    combat: 50,
    hp: 45,
  },
  {
    monster: "Body Golem",
    member: false,
    combat: 50,
    hp: 60,
  },
  {
    monster: "Vampyre Juvinate (lvl50)",
    member: true,
    combat: 50,
    hp: 60,
  },
  {
    monster: "Sulphur Lizard",
    member: true,
    combat: 50,
    hp: 50,
  },
  {
    monster: "Sigmund",
    member: true,
    combat: 50,
    hp: 60,
  },
  {
    monster: "Zombie (lvl50)",
    member: true,
    combat: 50,
    hp: 48,
  },
  {
    monster: "Skeleton fremennik",
    member: true,
    combat: 50,
    hp: 35,
  },
  {
    monster: "Undead Lumberjack (lvl50)",
    member: true,
    combat: 50,
    hp: 14,
  },
  {
    monster: "Animated spade",
    member: true,
    combat: 50,
    hp: 40,
  },
];
