import { faL } from "@fortawesome/free-solid-svg-icons";

const OSRS_MONSTERS = [
  // Level 1 to 10
  {
    monster: "Evil Creature",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Chicken",
    member: false,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Chinchompa (Hunter)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Gnome",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Gnome Woman",
    member: true,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Ragnar (Miscellania)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Duckling",
    member: false,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Spider",
    member: false,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Gnome child",
    member: true,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Einar",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Duck",
    member: false,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Gnome troop",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Rat",
    member: false,
    combat: 1,
    hp: 2,
  },
  {
    monster: "Target",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Halla (miscellania)",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Thorhild",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Undead chicken",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Rabbit",
    member: true,
    combat: 1,
    hp: 3,
  },
  {
    monster: "Alrik",
    member: true,
    combat: 1,
    hp: 1,
  },
  {
    monster: "Man",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rannveig",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Ram",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Giant spider",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Rusty",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rabbit (Prifddinas)",
    member: true,
    combat: 2,
    hp: 2000,
  },
  {
    monster: "Narf",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Rooster (lvl2)",
    member: true,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Rooster (lvl3)",
    member: true,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Entrana firebird",
    member: true,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Seagull",
    member: false,
    combat: 2,
    hp: 6,
  },
  {
    monster: "Skraeling (Etceteria)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Hengel",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Goblin",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Ragnvald",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Imp",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Jonny the beard",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Jeff",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Skraeling (Etceteria)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Penguin",
    member: true,
    combat: 2,
    hp: 4,
  },
  {
    monster: "Cow calf",
    member: false,
    combat: 2,
    hp: 6,
  },
  {
    monster: "Undead cow",
    member: false,
    combat: 2,
    hp: 8,
  },
  {
    monster: "Skraeling (Miscellania)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Valgerd",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Anja",
    member: false,
    combat: 2,
    hp: 7,
  },
  {
    monster: "Carnivorous chinchompa",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Black chinchompa (Hunter)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Broddi",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Wormbrain",
    member: false,
    combat: 2,
    hp: 5,
  },
  {
    monster: "Thora (Miscellania)",
    member: true,
    combat: 2,
    hp: 1,
  },
  {
    monster: "Zombie rat",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Pheasant",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Monkey",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Monk",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Cave goblin",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Sleepwalker",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Giant rat",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Sleepwalker",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Seagull (Icyene Graveyard)",
    member: true,
    combat: 3,
    hp: 10,
  },
  {
    monster: "Gardener",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Drunken man",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Pheasant",
    member: false,
    combat: 3,
    hp: 5,
  },
  {
    monster: "Cuffs",
    member: false,
    combat: 3,
    hp: 7,
  },
  {
    monster: "Eadburg",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "ceolburg",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "Hygd",
    member: true,
    combat: 4,
    hp: 10,
  },
  {
    monster: "Snake (desert)",
    member: true,
    combat: 5,
    hp: 6,
  },
  {
    monster: "Servant (Burthorpe)",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Snake",
    member: false,
    combat: 5,
    hp: 6,
  },
  {
    monster: "Gnome Driver",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Gnome Archer",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Highwayman",
    member: false,
    combat: 5,
    hp: 13,
  },
  {
    monster: "Gnome Mage",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Penda",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Ocga",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Frog",
    member: false,
    combat: 5,
    hp: 8,
  },
  {
    monster: "Bird",
    member: true,
    combat: 5,
    hp: 5,
  },
  {
    monster: "Bird (lvl11)",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Boar (lvl5)",
    member: true,
    combat: 5,
    hp: 5,
  },
  {
    monster: "Boar (lvl7)",
    member: true,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Breoca",
    member: true,
    combat: 5,
    hp: 10,
  },
  {
    monster: "Bat",
    member: true,
    combat: 6,
    hp: 8,
  },
  {
    monster: "Mugger",
    member: false,
    combat: 6,
    hp: 8,
  },
  {
    monster: "Chompy bird",
    member: true,
    combat: 6,
    hp: 10,
  },
  {
    monster: "Cave bug",
    member: true,
    combat: 6,
    hp: 5,
  },
  {
    monster: "Farmer",
    member: false,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Dwarf (lvl7)",
    member: false,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dwarf (lvl10)",
    member: false,
    combat: 10,
    hp: 16,
  },
  {
    monster: "Dwarf (lvl11)",
    member: false,
    combat: 11,
    hp: 18,
  },
  {
    monster: "Imp",
    member: false,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dark wizard",
    member: false,
    combat: 7,
    hp: 12,
  },
  {
    monster: "Dark wizard (lvl11)",
    member: true,
    combat: 11,
    hp: 15,
  },
  {
    monster: "Crawling hand (lvl7)",
    member: true,
    combat: 7,
    hp: 15,
  },
  {
    monster: "Crawling hand (lvl8)",
    member: true,
    combat: 8,
    hp: 16,
  },
  {
    monster: "Revenant imp",
    member: true,
    combat: 7,
    hp: 10,
  },
  {
    monster: "Dark warrior",
    member: false,
    combat: 8,
    hp: 17,
  },
  {
    monster: "Barbarian (lvl8)",
    member: false,
    combat: 8,
    hp: 14,
  },
  {
    monster: "Scarab Swarm (Tombs of Amascut)",
    member: true,
    combat: 8,
    hp: 10,
  },
  {
    monster: "Barbarian (lvl9)",
    member: false,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Barbarian (lvl10)",
    member: false,
    combat: 10,
    hp: 18,
  },
  {
    monster: "Barbarian (Barbarian Camp)",
    member: true,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Wizard",
    member: false,
    combat: 9,
    hp: 14,
  },
  {
    monster: "Blessed giant rat",
    member: true,
    combat: 9,
    hp: 30,
  },
  {
    monster: "Al Kharid warrior",
    member: false,
    combat: 9,
    hp: 19,
  },
  {
    monster: "Myre Blamish Snail",
    member: true,
    combat: 9,
    hp: 8,
  },
  {
    monster: "Myre Blamish Snail (Pointed)",
    member: true,
    combat: 10,
    hp: 13,
  },
  {
    monster: "Ochre Blamish Snail (Round)",
    member: true,
    combat: 10,
    hp: 10,
  },
  {
    monster: "Ochre Blamish Snail (Pointed)",
    member: true,
    combat: 15,
    hp: 20,
  },
  {
    monster: "Jubbly bird",
    member: true,
    combat: 9,
    hp: 20,
  },
  {
    monster: "Thug",
    member: true,
    combat: 9,
    hp: 18,
  },
  {
    monster: "Rowdy slave",
    member: true,
    combat: 10,
    hp: 16,
  },
  {
    monster: "Big frog",
    member: true,
    combat: 10,
    hp: 18,
  },
  {
    monster: "Guard (dwarf)",
    member: false,
    combat: 10,
    hp: 16,
  },
  // Level 11 to 20
  {
    monster: "Cave goblin miner",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Plague frog",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Shipyard worker",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Wolf (lvl11)",
    member: false,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Goblin (Vault of War)",
    member: false,
    combat: 11,
    hp: 7,
  },
  {
    monster: "Animated Bronze Armour",
    member: true,
    combat: 11,
    hp: 10,
  },
  {
    monster: "Mourner (lvl11)",
    member: true,
    combat: 11,
    hp: 19,
  },
  {
    monster: "Venenatis' Spiderling",
    member: true,
    combat: 12,
    hp: 5,
  },
  {
    monster: "Small Lizard",
    member: true,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Dungeon rat",
    member: true,
    combat: 12,
    hp: 12,
  },
  {
    monster: "Grave scorpion",
    member: true,
    combat: 12,
    hp: 12,
  },
  {
    monster: "H.A.M. Guard (lvl12)",
    member: true,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Spindel's Spiderling",
    member: true,
    combat: 12,
    hp: 5,
  },
  {
    monster: "Goblin (God Wars Dungeon) Banner",
    member: true,
    combat: 12,
    hp: 3,
  },
  {
    monster: "Enraged Boar",
    member: false,
    combat: 12,
    hp: 25,
  },
  {
    monster: "Goblin (God Wars Dungeon)",
    member: false,
    combat: 12,
    hp: 15,
  },
  {
    monster: "Goblin (lvl13)",
    member: false,
    combat: 13,
    hp: 13,
  },
  {
    monster: "Crawling hand (lvl12)",
    member: false,
    combat: 12,
    hp: 19,
  },
  {
    monster: "Minotaur",
    member: false,
    combat: 12,
    hp: 10,
  },
  {
    monster: "Icefiend",
    member: true,
    combat: 13,
    hp: 15,
  },
  {
    monster: "Giant frog",
    member: false,
    combat: 13,
    hp: 23,
  },
  {
    monster: "Rock Crab",
    member: true,
    combat: 13,
    hp: 50,
  },
  {
    monster: "Skeleton (The Restless Ghost)",
    member: false,
    combat: 13,
    hp: 18,
  },
  {
    monster: "Giant mosquito",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Hazeel Cultist",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Mourner (boss)",
    member: true,
    combat: 13,
    hp: 19,
  },
  {
    monster: "Summoned Zombie",
    member: true,
    combat: 13,
    hp: 22,
  },
  {
    monster: "Alomone",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Kebbit",
    member: true,
    combat: 13,
    hp: 50,
  },
  {
    monster: "Air wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Earth wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Water wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Fire wizard",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Flawed Golem",
    member: false,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Zombie (lvl13)",
    member: false,
    combat: 13,
    hp: 22,
  },
  {
    monster: "Disciple of Iban",
    member: true,
    combat: 13,
    hp: 20,
  },
  {
    monster: "Clivet",
    member: true,
    combat: 13,
    hp: 25,
  },
  {
    monster: "Large mosquito",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Chaos druid",
    member: true,
    combat: 13,
    hp: 3,
  },
  {
    monster: "Thief (Monk's Friend)",
    member: true,
    combat: 14,
    hp: 17,
  },
  {
    monster: "River troll",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Wolf (lvl14)",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Scorpion (lvl14)",
    member: true,
    combat: 14,
    hp: 17,
  },
  {
    monster: "Rock Golem (lvl14)",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Imp Champion",
    member: true,
    combat: 14,
    hp: 40,
  },
  {
    monster: "Woman (West Ardougne)",
    member: true,
    combat: 14,
    hp: 23,
  },
  {
    monster: "Tree spirit",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Lucien",
    member: true,
    combat: 14,
    hp: 25,
  },
  {
    monster: "Scorpia's offspring",
    member: true,
    combat: 15,
    hp: 2,
  },
  {
    monster: "Sand Crab",
    member: true,
    combat: 15,
    hp: 60,
  },
  {
    monster: "Rogue (lvl15)",
    member: true,
    combat: 15,
    hp: 17,
  },
  {
    monster: "Revenant goblin",
    member: true,
    combat: 15,
    hp: 14,
  },
  {
    monster: "Stag",
    member: true,
    combat: 15,
    hp: 19,
  },
  {
    monster: "Bear Cub",
    member: true,
    combat: 15,
    hp: 20,
  },
  {
    monster: "Forester (Woodcutting Guild)",
    member: true,
    combat: 15,
    hp: 17,
  },
  {
    monster: "Bark Blamish Snail",
    member: true,
    combat: 15,
    hp: 22,
  },
  {
    monster: "Barbarian (lvl15)",
    member: true,
    combat: 15,
    hp: 22,
  },
  {
    monster: "Unicorn",
    member: false,
    combat: 15,
    hp: 19,
  },
  {
    monster: "Thief Varrock",
    member: false,
    combat: 16,
    hp: 17,
  },
  {
    monster: "Skeleton Mage (lvl16)",
    member: true,
    combat: 16,
    hp: 17,
  },
  {
    monster: "Goblin (Vault of War)",
    member: false,
    combat: 16,
    hp: 22,
  },
  {
    monster: "Tormented Soul",
    member: true,
    combat: 16,
    hp: 20,
  },
  {
    monster: "Barbarian (lvl17)",
    member: false,
    combat: 16,
    hp: 20,
  },
  {
    monster: "Monk of Zamorak",
    member: false,
    combat: 17,
    hp: 10,
  },
  {
    monster: "Mosquito swarm (lvl17)",
    member: true,
    combat: 17,
    hp: 9,
  },
  {
    monster: "Soulless",
    member: true,
    combat: 18,
    hp: 24,
  },
  {
    monster: "Zombie (lvl18)",
    member: false,
    combat: 18,
    hp: 24,
  },
  {
    monster: "H.A.M. Guard (lvl18)",
    member: true,
    combat: 18,
    hp: 20,
  },
  {
    monster: "Icefiend",
    member: true,
    combat: 18,
    hp: 20,
  },
  {
    monster: "Locust",
    member: true,
    combat: 18,
    hp: 27,
  },
  {
    monster: "Pirate Guard",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Ghost (lvl19)",
    member: false,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Guard (Hosidius)",
    member: true,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Fox",
    member: true,
    combat: 19,
    hp: 30,
  },
  {
    monster: "Zamorak crafter",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Black bear",
    member: true,
    combat: 19,
    hp: 25,
  },
  {
    monster: "Tower Archer",
    member: true,
    combat: 19,
    hp: 30,
  },
  {
    monster: "Witch's experiment Skavid",
    member: true,
    combat: 19,
    hp: 21,
  },
  {
    monster: "Suit of armour",
    member: true,
    combat: 19,
    hp: 29,
  },
  {
    monster: "Guard (Doric's hut)",
    member: false,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Khazard trooper Spear",
    member: true,
    combat: 19,
    hp: 22,
  },
  {
    monster: "Scarred imp",
    member: true,
    combat: 19,
    hp: 25,
  },
];
